# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WeatherApp1' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WeatherApp1
  pod 'Alamofire', '~>4.7'
  pod 'SwiftyJSON', '~>4.0'
  pod 'NVActivityIndicatorView'
  pod 'RecastAI'

  target 'WeatherApp1Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WeatherApp1UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
